Updated deployment checklist for outgoing URL patterns
FlowCrypt/flowcrypt-docs pull request #103
Opened 2021-01-22 23:28 UTC by bilalashraf123

Closes issue #102 
Updated deployment checklist for outgoing URL patterns of different FlowCrypt services.

2021-01-23 07:30 UTC, tomholub requested changes
Thank you - the primary thing to fix is to make it general and mention which properties affect which urls exactly. I've commented on the EAP to show what I meant, but this applies to all services.

2021-01-23 07:30 UTC, tomholub commented on _pages/technical/enterprise/configuration/deployment-checklist.md
> +| https://fes.flowcrypt.com/* | `GET` | Internal | application/json | Use to fetch organization rules per domain. |
You'd have to say `htps://<FES-DOMAIN>/*`.

For future-proofing, let's put `GET` `PUT` `POST` `DELETE`

2021-01-23 07:30 UTC, tomholub commented on _pages/technical/enterprise/configuration/deployment-checklist.md
> +| https://ekm.flowcrypt.com/* | `GET and PUT` | Internal | application/json | Use to get and update information about users and their keys. |
`https://<EKM-DOMAIN>/*` and also let's use `GET` `PUT` `POST` `DELETE`

2021-01-23 07:30 UTC, tomholub commented on _pages/technical/enterprise/configuration/deployment-checklist.md
> +| https://wkd.flowcrypt.com/* | `GET` | Internal | application/json | Use to get public keys of the users. |
`https://<WKD-DOMAIN>/*`

2021-01-23 07:30 UTC, tomholub commented on _pages/technical/enterprise/configuration/deployment-checklist.md
> +| https://fkm.eu.auth0.com/token/* | `POST` | External | application/json | Auth0 OIDC token endpoint for admin ID token - (Note:- Unable to find it in code about token endpoint) |
- we use implicit grant flow, there is no `https://fkm.eu.auth0.com/token/
 - `https://fkm.eu.auth0.com/` is just an example from our internal testing, but does not reflect customer installations and is not in any way helpful to the customer. Customer will use their own IdP.

The right answer here is `url from auth.admin.openid.authorize.url, or authorization_endpoint in openid-configuration`

2021-01-23 07:30 UTC, tomholub commented on _pages/technical/enterprise/configuration/deployment-checklist.md
> +| https://fkm.eu.auth0.com/.well-known/jwks.json | `GET` | External | application/json | Use to fetch JWKs to verify the admin OIDC token signature. |
As above, this goes from a particular property either in properties file or from openid-configuration

2021-01-23 07:30 UTC, tomholub commented on _pages/technical/enterprise/configuration/deployment-checklist.md
> +| https://log-instance/* | `POST` | Internal | (Note: Not sure) | Use to send log events in case audit log service is running on HTTPS endpoint. Not required, if audit log is to be writtrn to file sy
Let's write the URL as `depends on logging configuration`, leave out the method, leave out Internal (it's possible to log to cloud). For comment use "Logging calls expected when StackdriverLogger or SplunkHttpLogger is configured. Not needed for StdoutLogger and FileLogger."

2021-01-23 07:30 UTC, tomholub commented on _pages/technical/enterprise/configuration/deployment-checklist.md
> +
This is missing information that the app will make a call to `https://<ISSUER>/.well-known/openid-configuration` to retrieve JWKS url and authorization URL, if any of these are not set in respective properties file (please mention which one). When using proxy, it's recommended to explicitly configure these two urls in the properties file.

2021-01-24 00:24 UTC, bilalashraf123 commented on _pages/technical/enterprise/configuration/deployment-checklist.md
> +| https://fes.flowcrypt.com/* | `GET` | Internal | application/json | Use to fetch organization rules per domain. |
Done.

2021-01-24 00:24 UTC, bilalashraf123 commented on _pages/technical/enterprise/configuration/deployment-checklist.md
> +| https://ekm.flowcrypt.com/* | `GET and PUT` | Internal | application/json | Use to get and update information about users and their keys. |
Done.

2021-01-24 00:25 UTC, bilalashraf123 commented on _pages/technical/enterprise/configuration/deployment-checklist.md
> +| https://wkd.flowcrypt.com/* | `GET` | Internal | application/json | Use to get public keys of the users. |
Done.

2021-01-24 00:25 UTC, bilalashraf123 commented on _pages/technical/enterprise/configuration/deployment-checklist.md
> +| https://fkm.eu.auth0.com/token/* | `POST` | External | application/json | Auth0 OIDC token endpoint for admin ID token - (Note:- Unable to find it in code about token endpoint) |
Done. Also removed the login URL.

2021-01-24 00:25 UTC, bilalashraf123 commented on _pages/technical/enterprise/configuration/deployment-checklist.md
> +| https://fkm.eu.auth0.com/.well-known/jwks.json | `GET` | External | application/json | Use to fetch JWKs to verify the admin OIDC token signature. |
Done.

2021-01-24 00:25 UTC, bilalashraf123 commented on _pages/technical/enterprise/configuration/deployment-checklist.md
> +| https://log-instance/* | `POST` | Internal | (Note: Not sure) | Use to send log events in case audit log service is running on HTTPS endpoint. Not required, if audit log is to be writtrn to file sy
Done.

2021-01-24 00:36 UTC, bilalashraf123 commented on _pages/technical/enterprise/configuration/deployment-checklist.md
> +
Done.

2021-01-24 07:37 UTC, tomholub requested changes
It's much better - still found some inconsistencies or improvements

2021-01-24 07:37 UTC, tomholub commented on _pages/technical/enterprise/configuration/deployment-checklist.md
> +| `https://<ISSUER>/.well-known/openid-configuration` | `GET` | External | application/json | Use to fetch JWK URLs for end users and admins if `auth.enduser.openid.jwks` and `auth.admin.openid.jwks`
There would be two request paths on FES here: one for `https://<enduser-issuer>/.well-known/openid-configuration` and one for `https://<admin-issuer>/.well-known/openid-configuration` so I'd make two lines (applies to EKM too)

2021-01-24 07:37 UTC, tomholub commented on _pages/technical/enterprise/configuration/deployment-checklist.md
> +| URL from `auth.admin.openid.authorize.url` in properties file or `authorization_endpoint` in openid-configuration | `GET` | External | Redirect Location Header | Auth0 OIDC authorization endpoint f
This URL is not called by the EAP. The user is forwarded to this URL, therefore the URL is loaded from user's browser, not subject to the proxy that restricts the EAP.

2021-01-24 07:37 UTC, tomholub commented on _pages/technical/enterprise/configuration/deployment-checklist.md
> +| `https://<ISSUER>/.well-known/openid-configuration` | `GET` | External | application/json | Use to fetch JWK URLs for admins if `auth.admin.openid.jwks` is not present in properties file. |
"if `auth.admin.openid.jwks` or `auth.admin.openid.authorize.url` is not present in properties file."

2021-01-24 07:37 UTC, tomholub commented on _pages/technical/enterprise/configuration/deployment-checklist.md
> +| `https://<ISSUER>/.well-known/openid-configuration` | `GET` | External | application/json | Use to fetch JWK URLs for end users and admins if `auth.enduser.openid.jwks` and `auth.admin.openid.jwks`
Here also to separate

2021-01-24 07:37 UTC, tomholub commented on _pages/technical/enterprise/configuration/deployment-checklist.md
> +| KMIP host | `TCP` | Internal | Socket based | KMIP server for storing infrastructure keys. |
I'd add optional here to the description

2021-01-24 07:37 UTC, tomholub commented on _pages/technical/enterprise/configuration/deployment-checklist.md
> +| `https://<WKD-DOMAIN>/*` | `PUT` | Internal | application/json | Use to push end user public keys |
Let's add "(only when configured with Push Sync)"

2021-01-24 07:37 UTC, tomholub commented on _pages/technical/enterprise/configuration/deployment-checklist.md
>  ### FlowCrypt World Key Directory
It's called Web Key Directory. But I recall doing the same typo somewhere - did you get this name from elsewhere in our projects?

2021-01-24 07:37 UTC, tomholub commented on _pages/technical/enterprise/configuration/deployment-checklist.md
> +| RDBMS host | `TCP` | Internal | Socket based | RDBMS server for storage of end users and their keys. |
Let's say `EKM RDBMS host` - it may be different one then WKD. Especially if WKD is in DMZ while EKM is in LAN.

2021-01-24 07:37 UTC, tomholub commented on _pages/technical/enterprise/configuration/deployment-checklist.md
> +| RDBMS host | `TCP` | Internal | Socket based | RDBMS server for storage of end user public keys. |
Let's say `WKD DRBMS host`

2021-01-24 07:37 UTC, tomholub commented on _pages/technical/enterprise/configuration/deployment-checklist.md
> +| RDBMS host | `TCP` | Internal | Socket based | RDBMS server for storage of end user public keys. |
Also missing logging on WKD

2021-01-24 07:37 UTC, tomholub commented on _pages/technical/enterprise/configuration/deployment-checklist.md
> +| `https://<ISSUER>/.well-known/openid-configuration` | `GET` | External | application/json | Use to fetch JWK URLs for end users and admins if `auth.enduser.openid.jwks` and `auth.admin.openid.jwks`
Missing logging on FES

2021-01-24 20:56 UTC, bilalashraf123 commented on _pages/technical/enterprise/configuration/deployment-checklist.md
> +| `https://<ISSUER>/.well-known/openid-configuration` | `GET` | External | application/json | Use to fetch JWK URLs for end users and admins if `auth.enduser.openid.jwks` and `auth.admin.openid.jwks`
done

2021-01-24 20:56 UTC, bilalashraf123 commented on _pages/technical/enterprise/configuration/deployment-checklist.md
> +| URL from `auth.admin.openid.authorize.url` in properties file or `authorization_endpoint` in openid-configuration | `GET` | External | Redirect Location Header | Auth0 OIDC authorization endpoint f
removed.

2021-01-24 20:56 UTC, bilalashraf123 commented on _pages/technical/enterprise/configuration/deployment-checklist.md
> +| `https://<ISSUER>/.well-known/openid-configuration` | `GET` | External | application/json | Use to fetch JWK URLs for admins if `auth.admin.openid.jwks` is not present in properties file. |
done

2021-01-24 20:57 UTC, bilalashraf123 commented on _pages/technical/enterprise/configuration/deployment-checklist.md
> +| `https://<ISSUER>/.well-known/openid-configuration` | `GET` | External | application/json | Use to fetch JWK URLs for end users and admins if `auth.enduser.openid.jwks` and `auth.admin.openid.jwks`
done

2021-01-24 20:57 UTC, bilalashraf123 commented on _pages/technical/enterprise/configuration/deployment-checklist.md
> +| KMIP host | `TCP` | Internal | Socket based | KMIP server for storing infrastructure keys. |
done

2021-01-24 20:57 UTC, bilalashraf123 commented on _pages/technical/enterprise/configuration/deployment-checklist.md
> +| `https://<WKD-DOMAIN>/*` | `PUT` | Internal | application/json | Use to push end user public keys |
done

2021-01-24 20:59 UTC, bilalashraf123 commented on _pages/technical/enterprise/configuration/deployment-checklist.md
>  ### FlowCrypt World Key Directory
It's web key directoy in the code. Not sure where I picked it. I searched the code base but did not find world key directory world this time.

2021-01-24 20:59 UTC, bilalashraf123 commented on _pages/technical/enterprise/configuration/deployment-checklist.md
> +| RDBMS host | `TCP` | Internal | Socket based | RDBMS server for storage of end users and their keys. |
done

2021-01-24 20:59 UTC, bilalashraf123 commented on _pages/technical/enterprise/configuration/deployment-checklist.md
> +| RDBMS host | `TCP` | Internal | Socket based | RDBMS server for storage of end user public keys. |
done

2021-01-24 20:59 UTC, bilalashraf123 commented on _pages/technical/enterprise/configuration/deployment-checklist.md
> +| RDBMS host | `TCP` | Internal | Socket based | RDBMS server for storage of end user public keys. |
done

2021-01-24 20:59 UTC, bilalashraf123 commented on _pages/technical/enterprise/configuration/deployment-checklist.md
> +| `https://<ISSUER>/.well-known/openid-configuration` | `GET` | External | application/json | Use to fetch JWK URLs for end users and admins if `auth.enduser.openid.jwks` and `auth.admin.openid.jwks`
done

2021-01-24 21:46 UTC, tomholub approved these changes
Looks good, thanks!

2021-01-24 21:47 UTC, merged